### ISSUE TITLE
Replace main page footer 

### ISSUE THREAD

**Issue by mzdaniel** [mzdaniel/pybay_front_end#6]
Using the [HomePageVerbiage doc](https://docs.google.com/document/d/1mMf8YuY5Klx1ekoGzIbO674IP1T_E7eRwcp83z85iG8/edit?usp=sharing) replace the main page footer

**Comment by sfpython** [comment]
Just push the change. Please update the site.

**Comment by mzdaniel** [comment]
Done. Changes are live.

**Comment by sfpython** [comment]
Thanks Dan!  Yeah!
